custom-checks:
  - name: required-labels
    template: required-labels
    params:
      labels: ["app.kubernetes.io/name", "app.kubernetes.io/version"]
    description: "All resources must have required labels"

checks:
  include:
    - required-labels
    - run-as-non-root
    - no-read-only-root-fs
  exclude:
    - privileged-container  # We need this for some pods

exclude:
  - name: ".*-secret"
    reason: "Secrets are generated separately"
