name: Python Build and Lint (pylint)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-lint:
    name: Build & Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'  # Cache pip dependencies
        cache-dependency-path: requirements.txt  # Cache dependencies based on requirements.txt
        # This will cache the pip dependencies based on the requirements.txt file.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        echo "Running pylint..."
        pylint $(git ls-files '*.py') --disable=invalid-name --fail-under-test=8.0
