# Complete workflow that runs unit tests AND checks 90% coverage
name: Unit Tests and Coverage

on:
  push:
    branches: [main]
    paths:
      - scr/**
      - testing/**
jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

    - name: Run unit tests with coverage check
      run: |
        # This command does BOTH:
        # 1. Runs all your unit tests
        # 2. Checks that coverage is >= 35%
        python -m pytest testing/ -v \
          --cov=src \
          --cov-report=term-missing \
          --cov-fail-under=35

    - name: Test /version endpoint
      run: pytest testing/test_version.py
