name: Python Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Allow cancellation of workflow runs when a PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12']  # Specify Python versions to test
        os: [ubuntu-latest]
        include:
          # Add Windows and macOS testing for the latest Python version
          - python-version: '3.12'
            os: windows-latest
          - python-version: '3.12'
            os: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper coverage reporting

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Cache pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-xdist
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Run pytest
      run: |
        pytest --cov=./scr --cov-report=xml --cov-report=term -v


    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()  # Run even if tests fail
      with:
        name: pytest-results-${{ matrix.python-version }}-${{ matrix.os }}
        path: |
          coverage.xml
        retention-days: 30
